title: Dear It Professionals
description: Come and save the world
baseurl: ""
exclude: ['auto']
analytics_id: TBD
theme: jekyll-theme-cayman

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed
