version: '2'

services:
  dev:
    image: ruby:2.5.1 # matches https://pages.github.com/versions
    working_dir: /work
    command: ./run
    volumes:
      - .:/work
      - ruby2.5-gem-cache:/usr/local/bundle
    ports:
      - '4000:4000'
  prod:
    environment:
      - JEKYLL_ENV=production
    extends:
      service: dev

volumes:
  ruby2.5-gem-cache:
    external: true
